"""Typed App subclasses generated from the Nautobot OpenAPI schema.

Generated by scripts/generate_endpoints.py - do not edit by hand.
Source: https://demo.nautobot.com/api/swagger.json (Nautobot API 3.2.2 (3.2))

The endpoint annotations exist only for static analysis (autocomplete,
type checking); no attributes are created at runtime. App.__getattr__
builds every Endpoint dynamically, so endpoints missing from this list
still work, and the hint classes in hints_generated.pyi never exist at runtime.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from aiopynautobot.app import App

if TYPE_CHECKING:
    from aiopynautobot import hints_generated as hints


class CircuitsApp(App):
    circuit_terminations: hints.CircuitsCircuitTerminationsEndpoint
    circuit_types: hints.CircuitsCircuitTypesEndpoint
    circuits: hints.CircuitsCircuitsEndpoint
    provider_networks: hints.CircuitsProviderNetworksEndpoint
    providers: hints.CircuitsProvidersEndpoint


class CloudApp(App):
    cloud_accounts: hints.CloudCloudAccountsEndpoint
    cloud_network_prefix_assignments: hints.CloudCloudNetworkPrefixAssignmentsEndpoint
    cloud_networks: hints.CloudCloudNetworksEndpoint
    cloud_resource_types: hints.CloudCloudResourceTypesEndpoint
    cloud_service_network_assignments: hints.CloudCloudServiceNetworkAssignmentsEndpoint
    cloud_services: hints.CloudCloudServicesEndpoint


class CoreApp(App):
    render_jinja_template: hints.CoreRenderJinjaTemplateEndpoint


class DataValidationApp(App):
    data_compliance: hints.DataValidationDataComplianceEndpoint
    min_max_rules: hints.DataValidationMinMaxRulesEndpoint
    regex_rules: hints.DataValidationRegexRulesEndpoint
    required_rules: hints.DataValidationRequiredRulesEndpoint
    unique_rules: hints.DataValidationUniqueRulesEndpoint


class DcimApp(App):
    cable_types: hints.DcimCableTypesEndpoint
    cables: hints.DcimCablesEndpoint
    cables_to_cable_terminations: hints.DcimCablesToCableTerminationsEndpoint
    connected_device: hints.DcimConnectedDeviceEndpoint
    console_connections: hints.DcimConsoleConnectionsEndpoint
    console_port_templates: hints.DcimConsolePortTemplatesEndpoint
    console_ports: hints.DcimConsolePortsEndpoint
    console_server_port_templates: hints.DcimConsoleServerPortTemplatesEndpoint
    console_server_ports: hints.DcimConsoleServerPortsEndpoint
    controller_managed_device_groups: hints.DcimControllerManagedDeviceGroupsEndpoint
    controllers: hints.DcimControllersEndpoint
    device_bay_templates: hints.DcimDeviceBayTemplatesEndpoint
    device_bays: hints.DcimDeviceBaysEndpoint
    device_cluster_assignments: hints.DcimDeviceClusterAssignmentsEndpoint
    device_families: hints.DcimDeviceFamiliesEndpoint
    device_redundancy_groups: hints.DcimDeviceRedundancyGroupsEndpoint
    device_types: hints.DcimDeviceTypesEndpoint
    device_types_to_software_image_files: (
        hints.DcimDeviceTypesToSoftwareImageFilesEndpoint
    )
    devices: hints.DcimDevicesEndpoint
    front_port_templates: hints.DcimFrontPortTemplatesEndpoint
    front_ports: hints.DcimFrontPortsEndpoint
    interface_connections: hints.DcimInterfaceConnectionsEndpoint
    interface_redundancy_group_associations: (
        hints.DcimInterfaceRedundancyGroupAssociationsEndpoint
    )
    interface_redundancy_groups: hints.DcimInterfaceRedundancyGroupsEndpoint
    interface_templates: hints.DcimInterfaceTemplatesEndpoint
    interface_vdc_assignments: hints.DcimInterfaceVdcAssignmentsEndpoint
    interfaces: hints.DcimInterfacesEndpoint
    inventory_items: hints.DcimInventoryItemsEndpoint
    location_types: hints.DcimLocationTypesEndpoint
    locations: hints.DcimLocationsEndpoint
    manufacturers: hints.DcimManufacturersEndpoint
    module_bay_templates: hints.DcimModuleBayTemplatesEndpoint
    module_bays: hints.DcimModuleBaysEndpoint
    module_families: hints.DcimModuleFamiliesEndpoint
    module_types: hints.DcimModuleTypesEndpoint
    modules: hints.DcimModulesEndpoint
    platforms: hints.DcimPlatformsEndpoint
    power_connections: hints.DcimPowerConnectionsEndpoint
    power_feeds: hints.DcimPowerFeedsEndpoint
    power_outlet_templates: hints.DcimPowerOutletTemplatesEndpoint
    power_outlets: hints.DcimPowerOutletsEndpoint
    power_panels: hints.DcimPowerPanelsEndpoint
    power_port_templates: hints.DcimPowerPortTemplatesEndpoint
    power_ports: hints.DcimPowerPortsEndpoint
    rack_groups: hints.DcimRackGroupsEndpoint
    rack_reservations: hints.DcimRackReservationsEndpoint
    racks: hints.DcimRacksEndpoint
    rear_port_templates: hints.DcimRearPortTemplatesEndpoint
    rear_ports: hints.DcimRearPortsEndpoint
    software_image_files: hints.DcimSoftwareImageFilesEndpoint
    software_versions: hints.DcimSoftwareVersionsEndpoint
    virtual_chassis: hints.DcimVirtualChassisEndpoint
    virtual_device_contexts: hints.DcimVirtualDeviceContextsEndpoint


class ExtrasApp(App):
    approval_workflow_definitions: hints.ExtrasApprovalWorkflowDefinitionsEndpoint
    approval_workflow_stage_definitions: (
        hints.ExtrasApprovalWorkflowStageDefinitionsEndpoint
    )
    approval_workflow_stages: hints.ExtrasApprovalWorkflowStagesEndpoint
    approval_workflows: hints.ExtrasApprovalWorkflowsEndpoint
    computed_fields: hints.ExtrasComputedFieldsEndpoint
    config_context_schemas: hints.ExtrasConfigContextSchemasEndpoint
    config_contexts: hints.ExtrasConfigContextsEndpoint
    contact_associations: hints.ExtrasContactAssociationsEndpoint
    contacts: hints.ExtrasContactsEndpoint
    content_types: hints.ExtrasContentTypesEndpoint
    custom_field_choices: hints.ExtrasCustomFieldChoicesEndpoint
    custom_fields: hints.ExtrasCustomFieldsEndpoint
    custom_links: hints.ExtrasCustomLinksEndpoint
    dynamic_group_memberships: hints.ExtrasDynamicGroupMembershipsEndpoint
    dynamic_groups: hints.ExtrasDynamicGroupsEndpoint
    export_templates: hints.ExtrasExportTemplatesEndpoint
    external_integrations: hints.ExtrasExternalIntegrationsEndpoint
    file_proxies: hints.ExtrasFileProxiesEndpoint
    git_repositories: hints.ExtrasGitRepositoriesEndpoint
    graphql_queries: hints.ExtrasGraphqlQueriesEndpoint
    image_attachments: hints.ExtrasImageAttachmentsEndpoint
    job_buttons: hints.ExtrasJobButtonsEndpoint
    job_hooks: hints.ExtrasJobHooksEndpoint
    job_logs: hints.ExtrasJobLogsEndpoint
    job_queue_assignments: hints.ExtrasJobQueueAssignmentsEndpoint
    job_queues: hints.ExtrasJobQueuesEndpoint
    job_results: hints.ExtrasJobResultsEndpoint
    jobs: hints.ExtrasJobsEndpoint
    metadata_choices: hints.ExtrasMetadataChoicesEndpoint
    metadata_types: hints.ExtrasMetadataTypesEndpoint
    notes: hints.ExtrasNotesEndpoint
    object_changes: hints.ExtrasObjectChangesEndpoint
    object_metadata: hints.ExtrasObjectMetadataEndpoint
    relationship_associations: hints.ExtrasRelationshipAssociationsEndpoint
    relationships: hints.ExtrasRelationshipsEndpoint
    roles: hints.ExtrasRolesEndpoint
    saved_views: hints.ExtrasSavedViewsEndpoint
    scheduled_jobs: hints.ExtrasScheduledJobsEndpoint
    secrets: hints.ExtrasSecretsEndpoint
    secrets_groups: hints.ExtrasSecretsGroupsEndpoint
    secrets_groups_associations: hints.ExtrasSecretsGroupsAssociationsEndpoint
    static_group_associations: hints.ExtrasStaticGroupAssociationsEndpoint
    statuses: hints.ExtrasStatusesEndpoint
    tags: hints.ExtrasTagsEndpoint
    teams: hints.ExtrasTeamsEndpoint
    user_saved_view_associations: hints.ExtrasUserSavedViewAssociationsEndpoint
    webhooks: hints.ExtrasWebhooksEndpoint


class IpamApp(App):
    ip_address_ranges: hints.IpamIpAddressRangesEndpoint
    ip_address_to_interface: hints.IpamIpAddressToInterfaceEndpoint
    ip_addresses: hints.IpamIpAddressesEndpoint
    namespaces: hints.IpamNamespacesEndpoint
    prefix_location_assignments: hints.IpamPrefixLocationAssignmentsEndpoint
    prefixes: hints.IpamPrefixesEndpoint
    rirs: hints.IpamRirsEndpoint
    route_targets: hints.IpamRouteTargetsEndpoint
    services: hints.IpamServicesEndpoint
    vlan_groups: hints.IpamVlanGroupsEndpoint
    vlan_location_assignments: hints.IpamVlanLocationAssignmentsEndpoint
    vlans: hints.IpamVlansEndpoint
    vrf_device_assignments: hints.IpamVrfDeviceAssignmentsEndpoint
    vrf_prefix_assignments: hints.IpamVrfPrefixAssignmentsEndpoint
    vrfs: hints.IpamVrfsEndpoint


class LoadBalancersApp(App):
    certificate_profiles: hints.LoadBalancersCertificateProfilesEndpoint
    health_check_monitors: hints.LoadBalancersHealthCheckMonitorsEndpoint
    load_balancer_pool_member_certificate_profile_assignments: (
        hints.LoadBalancersLoadBalancerPoolMemberCertificateProfileAssignmentsEndpoint
    )
    load_balancer_pool_members: hints.LoadBalancersLoadBalancerPoolMembersEndpoint
    load_balancer_pools: hints.LoadBalancersLoadBalancerPoolsEndpoint
    virtual_server_certificate_profile_assignments: (
        hints.LoadBalancersVirtualServerCertificateProfileAssignmentsEndpoint
    )
    virtual_servers: hints.LoadBalancersVirtualServersEndpoint


class TenancyApp(App):
    tenant_groups: hints.TenancyTenantGroupsEndpoint
    tenants: hints.TenancyTenantsEndpoint


class UsersApp(App):
    groups: hints.UsersGroupsEndpoint
    permissions: hints.UsersPermissionsEndpoint
    tokens: hints.UsersTokensEndpoint
    users: hints.UsersUsersEndpoint


class VirtualizationApp(App):
    cluster_groups: hints.VirtualizationClusterGroupsEndpoint
    cluster_types: hints.VirtualizationClusterTypesEndpoint
    clusters: hints.VirtualizationClustersEndpoint
    interfaces: hints.VirtualizationInterfacesEndpoint
    virtual_machines: hints.VirtualizationVirtualMachinesEndpoint


class VpnApp(App):
    vpn_phase_1_policies: hints.VpnVpnPhase1PoliciesEndpoint
    vpn_phase_2_policies: hints.VpnVpnPhase2PoliciesEndpoint
    vpn_profile_phase_1_policy_assignments: (
        hints.VpnVpnProfilePhase1PolicyAssignmentsEndpoint
    )
    vpn_profile_phase_2_policy_assignments: (
        hints.VpnVpnProfilePhase2PolicyAssignmentsEndpoint
    )
    vpn_profiles: hints.VpnVpnProfilesEndpoint
    vpn_terminations: hints.VpnVpnTerminationsEndpoint
    vpn_tunnel_endpoints: hints.VpnVpnTunnelEndpointsEndpoint
    vpn_tunnels: hints.VpnVpnTunnelsEndpoint
    vpns: hints.VpnVpnsEndpoint


class WirelessApp(App):
    controller_managed_device_group_radio_profile_assignments: (
        hints.WirelessControllerManagedDeviceGroupRadioProfileAssignmentsEndpoint
    )
    controller_managed_device_group_wireless_network_assignments: (
        hints.WirelessControllerManagedDeviceGroupWirelessNetworkAssignmentsEndpoint
    )
    radio_profiles: hints.WirelessRadioProfilesEndpoint
    supported_data_rates: hints.WirelessSupportedDataRatesEndpoint
    wireless_networks: hints.WirelessWirelessNetworksEndpoint


APP_CLASSES: dict[str, type[App]] = {
    "circuits": CircuitsApp,
    "cloud": CloudApp,
    "core": CoreApp,
    "data-validation": DataValidationApp,
    "dcim": DcimApp,
    "extras": ExtrasApp,
    "ipam": IpamApp,
    "load-balancers": LoadBalancersApp,
    "tenancy": TenancyApp,
    "users": UsersApp,
    "virtualization": VirtualizationApp,
    "vpn": VpnApp,
    "wireless": WirelessApp,
}
