"""Regenerate the typed endpoint hints from a Nautobot OpenAPI schema.

Outputs two files:

- src/aiopynautobot/apps_generated.py - typed App subclasses (endpoint-name hints)
- src/aiopynautobot/hints_generated.pyi - stub-only per-endpoint classes with
  TypedDict-backed kwargs overloads for filter/get/count/create

Usage:

    uv run python scripts/generate_endpoints.py [schema_url] [token]

Defaults to the public demo instance, which runs a current Nautobot
release. Unlike NetBox's demo, every Nautobot instance requires
authentication even to read the schema, so the demo's documented
read-only token is the default rather than sending no credentials.

To generate against your own instance, or to pin a specific version with
the throwaway container pynautobot's dev stack uses:

    uv run python scripts/generate_endpoints.py \\
        https://nautobot.example.com/api/swagger.json "$NAUTOBOT_TOKEN"

    docker run -d -p 8080:8080 \\
        -e NAUTOBOT_SUPERUSER_API_TOKEN=0123456789abcdef0123456789abcdef01234567 \\
        ghcr.io/nautobot/nautobot-dev:3.2

The output is deterministic for a given schema, so rerunning without
upstream changes produces no diff.
"""

from __future__ import annotations

import keyword
import re
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

import httpx2

DEFAULT_URL = "https://demo.nautobot.com/api/swagger.json"
# The demo instance's documented public read-only token. Nautobot requires
# authentication for every route, including the schema, so there is no
# anonymous fallback the way demo.netbox.dev offers one.
DEFAULT_TOKEN = "a" * 40

SRC = Path(__file__).resolve().parent.parent / "src" / "aiopynautobot"

# List-view paths only: <app>/<endpoint>/. Detail and sub-routes
# (/{id}/, /notes/, /trace/, ...) don't match. Two Nautobot quirks versus
# NetBox: the /api prefix lives in the schema's `servers` entry rather than
# in each path, so it is optional here; and the app group allows dashes
# because of data-validation and load-balancers.
LIST_PATH = re.compile(r"^(?:/api)?/([a-z][a-z-]*)/([a-z0-9-]+)/$")

# Real attributes on App that an endpoint annotation must never shadow.
RESERVED = {"name", "endpoint", "choices", "config"}

# Query params that aren't filters: pagination is driven by all()/the
# client, the default filters by the Api constructor, and lookup variants
# (name__ic, id__gt...) fall through to the Any-kwargs overload rather
# than multiplying the hint size.
PARAM_EXCLUDE = {"limit", "offset", "format", "exclude_m2m", "include", "depth"}

# Endpoints whose runtime Endpoint is a subclass (see app.SPECIAL_ENDPOINTS);
# the stub must match or run() disappears from the hints.
ENDPOINT_BASES = {
    ("extras", "jobs"): "JobsEndpoint",
    ("extras", "graphql_queries"): "GraphqlEndpoint",
}

# Endpoints whose records are model subclasses; hints return those types
# so their helpers (available_ips, trace, napalm, ...) type-check.
MODEL_RETURNS = {
    ("circuits", "circuits"): "Circuits",
    ("circuits", "circuit_terminations"): "CircuitTerminations",
    ("cloud", "cloud_networks"): "CloudNetworks",
    ("cloud", "cloud_resource_types"): "CloudResourceTypes",
    ("cloud", "cloud_services"): "CloudServices",
    ("dcim", "cables"): "Cables",
    ("dcim", "console_ports"): "ConsolePorts",
    ("dcim", "console_server_ports"): "ConsoleServerPorts",
    ("dcim", "controller_managed_device_groups"): "ControllerManagedDeviceGroups",
    ("dcim", "controllers"): "Controllers",
    ("dcim", "device_types"): "DeviceTypes",
    ("dcim", "devices"): "Devices",
    ("dcim", "front_ports"): "FrontPorts",
    ("dcim", "interfaces"): "Interfaces",
    ("dcim", "platforms"): "Platforms",
    ("dcim", "power_outlets"): "PowerOutlets",
    ("dcim", "power_ports"): "PowerPorts",
    ("dcim", "racks"): "Racks",
    ("dcim", "rear_ports"): "RearPorts",
    ("extras", "config_contexts"): "ConfigContexts",
    ("extras", "custom_field_choices"): "CustomFieldChoices",
    ("extras", "custom_fields"): "CustomFields",
    ("extras", "dynamic_groups"): "DynamicGroups",
    ("extras", "external_integrations"): "ExternalIntegrations",
    ("extras", "git_repositories"): "GitRepositories",
    ("extras", "graphql_queries"): "GraphqlQueries",
    ("extras", "job_results"): "JobResults",
    ("extras", "jobs"): "Jobs",
    ("extras", "object_changes"): "ObjectChanges",
    ("extras", "relationships"): "Relationships",
    ("extras", "saved_views"): "SavedViews",
    ("extras", "secrets"): "Secrets",
    ("ipam", "ip_addresses"): "IpAddresses",
    ("ipam", "prefixes"): "Prefixes",
    ("users", "permissions"): "Permissions",
    ("users", "users"): "Users",
    ("virtualization", "virtual_machines"): "VirtualMachines",
}

APPS_HEADER = '''"""Typed App subclasses generated from the Nautobot OpenAPI schema.

Generated by scripts/generate_endpoints.py - do not edit by hand.
Source: {source} (Nautobot API {version})

The endpoint annotations exist only for static analysis (autocomplete,
type checking); no attributes are created at runtime. App.__getattr__
builds every Endpoint dynamically, so endpoints missing from this list
still work, and the hint classes in hints_generated.pyi never exist at runtime.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from aiopynautobot.app import App

if TYPE_CHECKING:
    from aiopynautobot import hints_generated as hints
'''

HINTS_HEADER = '''"""Stub-only kwargs hints generated from the Nautobot OpenAPI schema.

Generated by scripts/generate_endpoints.py - do not edit by hand.
Source: {source} (Nautobot API {version})

This module exists only as a stub (.pyi): it is never imported at
runtime, and every runtime endpoint object is a plain Endpoint (or a
models.py subclass). The TypedDicts carry filter-param and writable-
field names for autocomplete; values are Any so nothing is enforced,
and the trailing **kwargs: Any overloads keep custom-field filters
(cf_*), lookup expressions (name__isw=...), and app params legal.
"""

from typing import Any, TypedDict, Unpack, overload

from aiopynautobot.endpoint import Endpoint, GraphqlEndpoint, JobsEndpoint
from aiopynautobot.models import *
from aiopynautobot.response import Record, RecordSet
'''


def pascal(name: str) -> str:
    return "".join(part.capitalize() for part in name.split("_"))


def app_class_name(app: str) -> str:
    """data-validation -> DataValidation."""
    return "".join(part.capitalize() for part in app.split("-"))


def valid_keys(names: set[str]) -> list[str]:
    return sorted(
        n
        for n in names
        if n.isidentifier()
        and not keyword.iskeyword(n)
        and "__" not in n
        and not n.startswith("cf_")
        and n not in PARAM_EXCLUDE
    )


def schema_properties(schema: dict[str, Any], components: dict[str, Any]) -> set[str]:
    """Property names of a request schema, resolving $ref and allOf."""
    if "$ref" in schema:
        schema = components.get(schema["$ref"].rsplit("/", 1)[-1], {})
    props = set(schema.get("properties", {}))
    for part in schema.get("allOf", []):
        props |= schema_properties(part, components)
    return props


def filter_params(operation: dict[str, Any]) -> set[str]:
    return {
        p["name"] for p in operation.get("parameters", []) if p.get("in") == "query"
    }


def create_fields(operation: dict[str, Any], components: dict[str, Any]) -> set[str]:
    content = operation.get("requestBody", {}).get("content", {})
    schema = content.get("application/json", {}).get("schema", {})
    return schema_properties(schema, components)


def endpoint_stub(app: str, attr: str, filters: list[str], fields: list[str]) -> str:
    """One endpoint's TypedDicts + Endpoint subclass for hints_generated.pyi."""
    cls = f"{app_class_name(app)}{pascal(attr)}"
    record = MODEL_RETURNS.get((app, attr), "Record")
    base = ENDPOINT_BASES.get((app, attr), "Endpoint")
    out: list[str] = []
    if filters:
        out.append(f"class {cls}Filters(TypedDict, total=False):")
        out += [f"    {name}: Any" for name in filters]
        out.append("")
    if fields:
        out.append(f"class {cls}Fields(TypedDict, total=False):")
        out += [f"    {name}: Any" for name in fields]
        out.append("")
    out.append(f"class {cls}Endpoint({base}):")
    if filters:
        out += [
            "    @overload",
            f"    def filter(self, **kwargs: Unpack[{cls}Filters]) -> RecordSet: ...",
            "    @overload",
            "    def filter(self, **kwargs: Any) -> RecordSet: ...",
            "    @overload",
            f"    async def get(self, pk: str, /) -> {record} | None: ...",
            "    @overload",
            f"    async def get(self, **kwargs: Unpack[{cls}Filters]) -> {record} | None: ...",
            "    @overload",
            "    async def get(",
            "        self, pk: str | None = None, /, **kwargs: Any",
            f"    ) -> {record} | None: ...",
            "    @overload",
            f"    async def count(self, **kwargs: Unpack[{cls}Filters]) -> int: ...",
            "    @overload",
            "    async def count(self, **kwargs: Any) -> int: ...",
        ]
    if fields:
        out += [
            "    @overload",
            f"    async def create(self, **fields: Unpack[{cls}Fields]) -> {record}: ...",
            "    @overload",
            f"    async def create(self, objects: list[dict[str, Any]], /) -> list[{record}]: ...",
            # The fallback overload must match Endpoint.create exactly,
            # including its return type: list is invariant, so a narrowed
            # list[Devices] is not assignable to the base's list[Record]
            # and pyright would reject the whole override.
            "    @overload",
            "    async def create(",
            "        self, *args: dict[str, Any] | list[dict[str, Any]], **kwargs: Any",
            "    ) -> Record | list[Record]: ...",
        ]
    if not filters and not fields:
        out.append("    ...")
    return "\n".join(out)


def main() -> None:
    url = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_URL
    token = sys.argv[2] if len(sys.argv) > 2 else DEFAULT_TOKEN
    headers = {"Accept": "application/json", "Authorization": f"Token {token}"}
    resp = httpx2.get(url, headers=headers, follow_redirects=True, timeout=300)
    resp.raise_for_status()
    spec = resp.json()
    components = spec.get("components", {}).get("schemas", {})

    # app -> attr -> (filters, fields)
    apps: dict[str, dict[str, tuple[list[str], list[str]]]] = defaultdict(dict)
    for path, operations in spec["paths"].items():
        match = LIST_PATH.fullmatch(path)
        if not match:
            continue
        app, slug = match.groups()
        if app == "plugins":
            continue  # app endpoints depend on what the instance has installed
        attr = slug.replace("-", "_")
        if not attr.isidentifier() or attr in RESERVED:
            continue
        filters = valid_keys(filter_params(operations.get("get", {})))
        fields = valid_keys(create_fields(operations.get("post", {}), components))
        apps[app][attr] = (filters, fields)

    version = spec.get("info", {}).get("version", "unknown")

    apps_chunks = [APPS_HEADER.format(source=url, version=version)]
    hints_chunks = [HINTS_HEADER.format(source=url, version=version)]
    for app in sorted(apps):
        lines = [f"class {app_class_name(app)}App(App):"]
        for attr in sorted(apps[app]):
            filters, fields = apps[app][attr]
            hints_chunks.append(endpoint_stub(app, attr, filters, fields))
            lines.append(
                f"    {attr}: hints.{app_class_name(app)}{pascal(attr)}Endpoint"
            )
        apps_chunks.append("\n".join(lines))
    mapping = [f'    "{app}": {app_class_name(app)}App,' for app in sorted(apps)]
    apps_chunks.append(
        "APP_CLASSES: dict[str, type[App]] = {\n" + "\n".join(mapping) + "\n}"
    )

    (SRC / "apps_generated.py").write_text("\n\n\n".join(apps_chunks) + "\n")
    (SRC / "hints_generated.pyi").write_text("\n\n\n".join(hints_chunks) + "\n")
    total = sum(len(v) for v in apps.values())
    params = sum(len(f) for v in apps.values() for f, _ in v.values())
    print(
        f"wrote apps_generated.py + hints_generated.pyi ({total} endpoints, "
        f"{params} filter params, Nautobot {version})"
    )


if __name__ == "__main__":
    main()
